# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shortContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
