# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_shortcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='shortContent',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
